[project]
name = "llm-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lynix Dancho", email = "laredjyacine955@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "bm25s>=0.3.10",
    "cohere>=7.0.9",
    "datasets>=5.0.1",
    "deepeval>=4.2.0",
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "numpy>=2.4.6",
    "ollama>=0.6.2",
    "openai>=3.3.1",
    "pandas>=3.0.5",
    "pgvector>=0.5.0",
    "psycopg2>=2.9.12",
    "pydantic>=2.13.4",
    "pystemmer>=3.1.0",
    "qwen-tokenizer>=0.3.0",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
llm-api = "llm_api:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
